markdown: rdiscount
pygments: true
permalink: /delphi/posts/:title
auto: true
rdiscount:
  extensions: [smart]
title : Diego Selzlein
production_url : http://nerde.github.com/
description: "Stories, tutorials, codes, projects, thoughts and other things by Diego Aguir Selzlein."
disqus_shortname: nerde
analytics: UA-42080782-1
# gauges: 50f2b533613f5d7c8000000c
author :
  name : Diego Aguir Selzlein
  github : nerde
  # twitter : nerdee
