markdown: rdiscount
pygments: true
permalink: /posts/:title
auto: true
rdiscount:
  extensions: [smart]
title : Carlos Becker
production_url : http://nerde.github.com
description: "Througths, flamewars, utilities, tutorials, codes, projects and other things by Carlos Alexandro Becker."
disqus_shortname: nerde
analytics: UA-32899481-1
gauges: 50f2b533613f5d7c8000000c
author :
  name : Diego Aguir Selzlein
  github : nerde
  twitter : nerde
